package edu.northeastern.reporting;

import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVPrinter;
import org.apache.commons.csv.CSVRecord;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.*;
import java.util.stream.Collectors;

/**
 * This class compares the provided the oracle
 * with the report generated by the detectors.
 */
public class OracleEvaluator {

    private final File oracleFile;
    private final List<ReportStruct> detectedReports;
    private final String outputDirPath;

    public OracleEvaluator(File oracleFile, List<ReportStruct> detectedReports, String outputDirPath) {
        this.oracleFile = oracleFile;
        this.detectedReports = detectedReports;
        this.outputDirPath = outputDirPath;
    }

    /**
     * This function compares the expected and detected maps and
     * prints the confusion matrix results for
     * True Positives, False Positives, True Negatives and False Negatives along
     * with the recall, precision and F1 scores.
     */
    public void evaluateAndReport() {
        Map<String, Set<String>> expectedMap = parseOracleFile();
        Map<String, Set<String>> detectedMap = parseDetectedReports();

        generateComparisonCSV(expectedMap, detectedMap);

        Set<String> allFiles = new TreeSet<>(expectedMap.keySet());
        allFiles.addAll(detectedMap.keySet());
        allFiles.remove("");

        Set<String> allSmells = new TreeSet<>();
        expectedMap.values().forEach(allSmells::addAll);
        detectedMap.values().forEach(allSmells::addAll);

        Map<String, int[]> smellMetrics = new HashMap<>();
        for (String smell : allSmells) {
            smellMetrics.put(smell, new int[4]);
        }

        int totalTp = 0, totalFp = 0, totalFn = 0, totalTn = 0;

        List<String> missedSmellDetails = new ArrayList<>();

        for (String fileName : allFiles) {
            Set<String> expected = expectedMap.getOrDefault(fileName, Collections.emptySet());
            Set<String> detected = detectedMap.getOrDefault(fileName, Collections.emptySet());

            Set<String> truePositives = new HashSet<>(expected);
            truePositives.retainAll(detected);
            totalTp += truePositives.size();

            Set<String> falsePositives = new HashSet<>(detected);
            falsePositives.removeAll(expected);
            totalFp += falsePositives.size();

            Set<String> falseNegatives = new HashSet<>(expected);
            falseNegatives.removeAll(detected);

            if (!falseNegatives.isEmpty()) {
                for (String smell : falseNegatives) {
                    missedSmellDetails.add(String.format("  - %-20s : Missing [%s]", fileName, smell));
                }
            }
            totalFn += falseNegatives.size();

            if (expected.isEmpty() && detected.isEmpty()) {
                totalTn++;
            }

            for (String smell : allSmells) {
                boolean isExpected = expected.contains(smell);
                boolean isDetected = detected.contains(smell);

                int[] metrics = smellMetrics.get(smell);

                if (isExpected && isDetected) {
                    metrics[0]++;
                } else if (!isExpected && isDetected) {
                    metrics[1]++;
                } else if (isExpected && !isDetected) {
                    metrics[2]++;
                } else {
                    metrics[3]++;
                }
            }
        }

        double precision = (totalTp + totalFp == 0) ? 0.0 : (double) totalTp / (totalTp + totalFp);
        double recall = (totalTp + totalFn == 0) ? 0.0 : (double) totalTp / (totalTp + totalFn);
        double f1 = (precision + recall == 0) ? 0.0 : 2 * ((precision * recall) / (precision + recall));

        System.out.println("\n========================================");
        System.out.println("   STATICNOSE GLOBAL METRICS REPORT     ");
        System.out.println("========================================");
        System.out.printf("  Total Files Analyzed : %d\n", allFiles.size());
        System.out.println("----------------------------------------");
        System.out.printf("  Total TP: %-4d Total FP: %-4d\n", totalTp, totalFp);
        System.out.printf("  Total FN: %-4d Total TN: %-4d\n", totalFn, totalTn);
        System.out.println("----------------------------------------");
        System.out.printf("  Overall Precision : %.2f%%\n", precision * 100);
        System.out.printf("  Overall Recall    : %.2f%%\n", recall * 100);
        System.out.printf("  Overall F1-Score  : %.2f\n", f1);
        System.out.println("----------------------------------------");

        System.out.println("\n=========================================================================================");
        System.out.println("                         STATICNOSE PER-SMELL METRICS REPORT");
        System.out.println("=========================================================================================");
        System.out.printf("  %-24s | %7s | %4s | %4s | %4s | %4s | %9s | %8s | %4s\n",
                "Smell Name", "Samples", "TP", "FP", "FN", "TN", "Precision", "Recall", "F1");
        System.out.println("-----------------------------------------------------------------------------------------");

        for (String smell : allSmells) {
            int[] m = smellMetrics.get(smell);
            int tp = m[0], fp = m[1], fn = m[2], tn = m[3];

            int samples = tp + fn;

            double prec = (tp + fp == 0) ? 0.0 : (double) tp / (tp + fp);
            double rec = (tp + fn == 0) ? 0.0 : (double) tp / (tp + fn);
            double f1Smell = (prec + rec == 0) ? 0.0 : 2 * ((prec * rec) / (prec + rec));

            System.out.printf("  %-24s | %7d | %4d | %4d | %4d | %4d | %8.2f%% | %7.2f%% | %4.2f\n",
                    smell, samples, tp, fp, fn, tn, prec * 100, rec * 100, f1Smell);
        }
        System.out.println("=========================================================================================\n");

        if (!missedSmellDetails.isEmpty()) {
            System.out.println("  DETAILED FALSE NEGATIVES (MISSED):");
            missedSmellDetails.forEach(System.out::println);
        } else {
            System.out.println("  Perfect Recall! No smells were missed.");
        }
        System.out.println("========================================\n");
    }

    /**
     * This function parses the oracle file to create a map
     * of the file names to the expected code smells in them.
     * @return A map of file names to expected code smells
     */
    private Map<String, Set<String>> parseOracleFile() {
        Map<String, Set<String>> map = new HashMap<>();

        CSVFormat format = CSVFormat.DEFAULT.builder()
                .setHeader()
                .setSkipHeaderRecord(true)
                .setAllowMissingColumnNames(true)
                .build();

        try (FileReader reader = new FileReader(oracleFile);
             CSVParser parser = format.parse(reader)) {

            for (CSVRecord record : parser) {
                String fileName = record.get(0).trim();
                String rawSmells = record.get(1);

                map.put(fileName, cleanAndSplitSmells(rawSmells));
            }
        } catch (Exception e) {
            System.err.println("Failed to read Oracle file: " + e.getMessage());
        }
        return map;
    }

    /**
     * This function creates a map of files to the code smells
     * detected inside them.
     * @return A map of file names to the code smells detected in them
     */
    private Map<String, Set<String>> parseDetectedReports() {
        Map<String, Set<String>> map = new HashMap<>();

        for (ReportStruct report : detectedReports) {
            String fileName = Paths.get(report.getFilePath()).getFileName().toString();

            if (fileName.endsWith(".java")) {
                fileName = fileName.substring(0, fileName.length() - 5);
            }

            map.putIfAbsent(fileName, new HashSet<>());
            map.get(fileName).add(report.getSmellName());
        }
        return map;
    }

    /**
     * Function to create the comparison CSV report.
     * The comparison CSV contains the Expected Code Smells along with
     * the Detected Code Smells.
     * @param expectedMap the code smells expected from the oracle
     * @param detectedMap the actual code smells detected by the tool
     */
    private void generateComparisonCSV(Map<String, Set<String>> expectedMap, Map<String, Set<String>> detectedMap) {
        String outputPath = outputDirPath + "/staticnose-report/oracle_comparison.csv";
        File outFile = new File(outputPath);

        if (outFile.getParentFile() != null) {
            FileUtils.safeCreateDir(outFile.getParentFile().getAbsolutePath());
        }

        String[] HEADERS = {"File Name", "Expected Code Smells", "Detected Code Smells"};
        CSVFormat format = CSVFormat.DEFAULT.builder().setHeader(HEADERS).build();

        Set<String> allFiles = new HashSet<>(expectedMap.keySet());
        allFiles.addAll(detectedMap.keySet());

        try (FileWriter out = new FileWriter(outFile);
             CSVPrinter printer = new CSVPrinter(out, format)) {

            for (String fileName : allFiles) {
                Set<String> expected = expectedMap.getOrDefault(fileName, Collections.emptySet());
                Set<String> detected = detectedMap.getOrDefault(fileName, Collections.emptySet());

                printer.printRecord(
                        fileName,
                        formatSmellSet(expected),
                        formatSmellSet(detected)
                );
            }
            System.out.println("\nComparison CSV generated at: " + outputPath);
        } catch (IOException e) {
            System.err.println("Failed to write Comparison CSV: " + e.getMessage());
        }
    }

    /**
     * Helper function to convert a list of code smells in the oracle
     * into a set of string.
     * @param raw the string to convert from the oracle
     * @return the converted set of string
     */
    private Set<String> cleanAndSplitSmells(String raw) {
        if (raw == null || raw.trim().isEmpty()) return new HashSet<>();

        return Arrays.stream(raw.split(","))
                .map(s -> s.replaceAll("[\\[\\]'\"]", "").trim()) // Remove brackets and quotes
                .filter(s -> !s.isEmpty())
                .collect(Collectors.toSet());
    }

    /**
     * Helper function to revert a set of smell strings into
     * the list of code smells as is in the oracle
     * @param smells set of smell name string
     * @return string of list of code smells
     */
    private String formatSmellSet(Set<String> smells) {
        if (smells.isEmpty()) return "[]";
        return smells.stream()
                .map(smell -> "'" + smell + "'")
                .collect(Collectors.joining(", ", "[", "]"));
    }
}